export const appCopy = {
  app: {
    name: "Paws for Life",
    eyebrow: "Adăpost Canin Craiova",
    title: "Cățeluși disponibili pentru adopție",
    tagline:
      "Descoperă un cățeluș care îți poate deveni prieten pentru totdeauna.",
    sourceNotice: "Datele vin din anunțurile oficiale ale adăpostului.",
    sourceLink: "Anunțul adăpostului",
    lastSyncPrefix: "Ultima actualizare",
    menuOpen: "Meniu",
    deckView: "Descoperă",
    galleryView: "Galerie",
    menuClose: "Închide meniul",
  },
  filters: {
    label: "Filtre",
    open: "Filtre",
    close: "Închide filtrele",
    searchLabel: "Caută",
    searchPlaceholder: "nume, loc, culoare sau vârstă",
    sexLabel: "Sex",
    sizeLabel: "Talie",
    all: "Toți",
    female: "Femelă",
    male: "Mascul",
    unknown: "Necunoscut",
    small: "Mică",
    medium: "Medie",
    large: "Mare",
    reset: "Șterge filtrele",
  },
  deck: {
    next: "Următorul",
    like: "Salvează",
    verified: "Din evidența adăpostului",
    profilePhotoAction: "Vezi fotografia cățelușului",
    about: "Despre mine",
    lookingFor: "Caut o familie",
    swipeLeft: "Glisează spre stânga pentru urmatorul",
    swipeLeftAction: "următorul cățeluș",
    swipeRight: "Glisează spre dreapta pentru a salva",
    swipeRightAction: "salvează la preferați",
    profile: "Profilul meu",
    emptyTitle: "Ai cunoscut toți cățelușii de aici",
    emptyBody:
      "Încearcă alte filtre sau revino curând să vezi cine a mai sosit.",
    unavailable: "Nu mai este disponibil",
    registryPrefix: "Nr. de registru",
    captureDate: "Data capturării",
    captureLocation: "Locul capturării",
    approximateAge: "Vârstă aproximativă",
    sex: "Sex",
    size: "Talie",
    color: "Culoare",
    characteristics: "Alte caracteristici",
  },
  match: {
    title: "ți-a cucerit inima!",
    body: "L-am adăugat în lista ta de cățelușii preferați.",
    bodyFemale: "Am adăugat-o în lista ta de cățelușii preferați.",
    close: "Continuă",
  },
  adoption: {
    ctaMale: "Adoptă-l pe",
    ctaFemale: "Adopt-o pe",
    ctaNeutral: "Adoptă acum:",
    cta: "Adoptă acum",
    title: "Cum poți adopta",
    intro: "Sună la adăpost și verifică pașii oficiali înainte de vizită.",
    addressLabel: "Adresa adăpostului",
    address: "Dolj, Craiova, Tarlaua 44 NP 311",
    mapsUrl: "https://maps.app.goo.gl/KdVBTt2Lj7HAGSkXA",
    dispatchPhoneLabel: "Dispecerat non-stop",
    dispatchPhone: "0251.422.733",
    shelterPhoneLabel: "Adăpost, 07:00-19:00",
    shelterPhone: "0722.328.442",
    scheduleLabel: "Program",
    weekdaySchedule: "Luni - vineri: 10:00 - 18:00",
    weekendSchedule: "Sâmbătă, duminică și sărbători legale: 11:00 - 13:00",
    linksLabel: "Linkuri utile",
    links: [
      {
        label: "Norme privind adopția",
        href: "https://www.adapostcanincraiova.ro/norme-privind-adoptia/",
      },
      {
        label: "Procedura de adopție",
        href: "https://www.adapostcanincraiova.ro/procedura-de-adoptie/",
      },
      {
        label: "Documente pentru adopție",
        href: "https://www.adapostcanincraiova.ro/documente-pentru-adoptie/",
      },
    ],
  },
  shareImage: {
    callMale: "Sună să îl adopți pe",
    callFemale: "Sună să o adopți pe",
    callNeutral: "Sună pentru adopția lui",
  },
  shortlist: {
    title: "Cățeluși preferați",
    open: "Cățeluși preferați",
    close: "Închide lista",
    empty:
      "Când un cățeluș îți atrage atenția, salvează-l aici ca să-l găsești ușor.",
    remove: "Mai caut puțin",
    countSuffix: "în lista de preferați",
  },
  gallery: {
    title: "Toți cățelușii",
    subtitle: "cățeluși disponibili",
    dogOfDay: "Cățelușul zilei",
    dogOfDayFallback: "Un cățeluș care își așteaptă familia.",
    meet: "Cunoaște",
    save: "Salvează",
    saved: "Salvat",
    quickFilters: "Filtre rapide",
    sortLabel: "Sortează după",
    recommended: "Recomandat",
    longestWaiting: "Așteaptă de cel mai mult timp",
    newestCapture: "Sosiți recent",
    recentlyAdded: "Apăruți recent pe site",
    young: "Tineri",
    adult: "Adulți",
    senior: "Seniori",
    loadingMore: "Se încarcă mai mulți cățeluși...",
    share: "Distribuie",
    shareDialogTitle: "Alege cum distribui",
    shareDialogDescription: "Trimite linkul sau o imagine pregatita pentru Facebook.",
    shareLink: "Distribuie linkul",
    shareProfileImage: "Distribuie imaginea profilului",
    shareStory: "Distribuie la story",
    sharePreparing: "Pregatim imaginea",
    shareLinkPreparing: "Pregatim linkul",
    shareDone: "Distribuit",
    downloaded: "Imagine descarcata",
    copied: "Link copiat",
    shareUnavailable: "Imaginea nu a putut fi pregatita",
    detailsBack: "Înapoi la cățeluși",
    detailTitle: "Profil de adopție",
    unavailableDetail:
      "Acest cățeluș nu mai apare ca disponibil pe site-ul adăpostului.",
  },
  status: {
    loading: "Se încarcă...",
    syncNever: "nu a fost făcută încă",
    syncFailed: "nu a reușit",
    imageAltPrefix: "Fotografia cățelușului din registru",
  },
} as const;

export type AppCopy = typeof appCopy;
